### ISSUE TITLE
 Транслировать в статус играющую музыку включается при воспроизведении музыки

### ISSUE THREAD

**Issue by abcdw** [v-kiniv/pulsar#1]
Прошу сделать возможность отключения этой фичи.

**Comment by v-kiniv** [comment]
Транслирование в статус не должно влючаться при воспроизведении. Эта функция включается только вручную.

**Comment by abcdw** [comment]
ну не знаю =) почему-то включается сама. а вообще в API есть http://vk.com/developers.php?o=-1&p=status.set

**Comment by v-kiniv** [comment]
API контакта не используется.

**Comment by v-kiniv** [comment]
Плеер собран из исходников или PPA?

**Comment by abcdw** [comment]
Собран из исходников. https://gist.github.com/79076b5da85361beefcb

**Comment by v-kiniv** [comment]
Можно подробней, каким образом это происходит?
Например, выключил трансляцию(иконка трансляции "потухла"), кликнул 2 раза на треке в плейлисте - трансляция сама включилась(иконка тоже поменялась?)

**Comment by abcdw** [comment]
ого, это оказывается иконка трансляции, не совсем очевидно. Просто она была нажата и все транслировалось в статус. Впорос решен.
